import Head from 'next/head'
import CategoriesComponent from "../components/Categories/CategoriesComponent";
import BlogComponent from "../components/Blog/BlogComponent";
import fs from 'fs'
import path from 'path'

function Home(props) {
  return (
    <div>
      <Head>
        <title>Ashutosh.dev - A place to learn Programming</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-auto">
          <CategoriesComponent />
          <BlogComponent Blogs={props} />
          <div></div>
      </div>

    </div>
  )
}

export async function getStaticProps(context) {
    let blog = new Array();
    const fileToRead = path.join(process.cwd(), '/data/articles.json')
    const data = JSON.parse(await fs.readFileSync(fileToRead))

    for (let index in data) {
        const catList = data[index].cached_tag_list
        blog.push({
            title: data[index].title,
            date: data[index].published_at,
            body: data[index].body_markdown,
            description: data[index].description,
            categories: catList,
            slug: data[index].slug
        });
    }

    // Reverse an Array
    const reverseData = blog.slice(0).reverse()

    return  {
        props: {
            sample_blogs: reverseData
        }
    }
}

export default Home