import Head from 'next/head'
import CategoriesComponent from "../components/Categories/CategoriesComponent";
import BlogComponent from "../components/Blog/BlogComponent";

import getAllBlogsData from "../Utilities/FileRead";

function Home(props) {
  return (
    <div>
      <Head>
        <title>Ashutosh.dev - A place to learn Programming</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-auto">
          <CategoriesComponent />
          <BlogComponent Blogs={props} />
          <div></div>
      </div>

    </div>
  )
}

export async function getStaticProps(context) {
    const data = getAllBlogsData('/data/articles.json')

    return  {
        props: {
            sample_blogs: data
        }
    }
}

export default Home
